quarkus.log.category."dev.ricardovm".level=DEBUG
quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n
quarkus.http.access-log.pattern="...traceId=%{X,traceId} spanId=%{X,spanId}"

mp.messaging.incoming.quote-responses.failure-strategy=dead-letter-queue
mp.messaging.incoming.quote-responses.dead-letter-queue.topic=quote-responses-dlq
mp.messaging.incoming.quote-responses.group.id=besttravel-front-bff
besttravel.quote.callback.ttl-seconds=30

mp.messaging.incoming.booking-responses.failure-strategy=dead-letter-queue
mp.messaging.incoming.booking-responses.dead-letter-queue.topic=booking-responses-dlq
mp.messaging.incoming.booking-responses.group.id=besttravel-front-bff
besttravel.booking.callback.ttl-seconds=30

vaadin.build.pnpm-enable=true
vaadin.build.ci-build=true
vaadin.build.frontend-directory=src/main/frontend
vaadin.build.optimize-bundle=true
