quarkus.bootstrap.workspace-discovery=true
quarkus.log.category."dev.ricardovm".level=DEBUG
quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n
quarkus.http.access-log.pattern="...traceId=%{X,traceId} spanId=%{X,spanId}"

mp.messaging.incoming.quote-responses.failure-strategy=dead-letter-queue
mp.messaging.incoming.quote-responses.dead-letter-queue.topic=quote-responses-dlq
besttravel.quote.callback.ttl-minutes=5

mp.messaging.incoming.booking-responses.failure-strategy=dead-letter-queue
mp.messaging.incoming.booking-responses.dead-letter-queue.topic=booking-responses-dlq
besttravel.booking.callback.ttl-minutes=3
