quarkus.log.category."dev.ricardovm".level=DEBUG
quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n

mp.messaging.incoming.quote-commands.failure-strategy=dead-letter-queue
mp.messaging.incoming.quote-commands.dead-letter-queue.topic=quote-commands-dlq
mp.messaging.incoming.quote-commands.group.id=besttravel-orchestrator-service

mp.messaging.incoming.booking-commands.failure-strategy=dead-letter-queue
mp.messaging.incoming.booking-commands.dead-letter-queue.topic=booking-commands-dlq
mp.messaging.incoming.booking-commands.group.id=besttravel-orchestrator-service

mp.messaging.incoming.quote-commands-dlq.connector=smallrye-kafka
mp.messaging.incoming.quote-commands-dlq.topic=quote-commands-dlq

mp.messaging.incoming.booking-commands-dlq.connector=smallrye-kafka
mp.messaging.incoming.booking-commands-dlq.topic=booking-commands-dlq
